# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06371b0e44580d2fc20081a85b0f5ee0f5796c6a884728d1acbb3536c45e3b66361512c323c5fed65dd711617059f2d2b51c5d4b75499251428af7b6bdf33678

test:
  secret_key_base: f7d4559df666a983430600ff8985cde124f95b6d5685391bc59bc29f25c0e6f698724cbbf5c22d52e0c6b0357722ad0d404df1454c07487e78d8bacc0b564e4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
